{ pkgs, config, inputs, ... }:
{
  programs.doom-emacs = {
    enable = true;
    doomDir = inputs.doom-config;
    tangleArgs = "--tag enabled config.org";
    emacs = pkgs.emacs-pgtk;
    extraBinPackages = with pkgs; [
      git
      fd
      ripgrep
      gcc
      gnumake
      semgrep
      # Nix
      nil
      nixd
      typos-lsp
      # Python
      python3Packages.python-lsp-server
      ruff
      # Spelling
      (aspellWithDicts (
        dicts: with dicts; [
          en
          en-computers
          en-science
        ]
      ))
      # Latex
      texlive.combined.scheme-medium
    ];
  };

  # --- API Secrets ---
  sops = {
    defaultSopsFile = ../../../secrets.yaml;
    defaultSopsFormat = "yaml";
    age.keyFile = "/home/james/.config/sops/age/keys.txt";
    secrets = {
      gpt_api_key = { };
      gemini_api_key = { };
      openrouter_api_key = { };
      deepseek_api_key = { };
    };
  };

  xdg.configFile."doom-secrets.el".text = ''
    ;; Generated by Nix, DO NOT EDIT!!!
    ;; Helper function to read a secret from a file path
    (defun my/read-secret (path)
      (when (file-exists-p path)
        (with-temp-buffer
          (insert-file-contents path)
          (string-trim (buffer-string)))))

    (defconst my-gpt-api-key (my/read-secret "${config.sops.secrets.gpt_api_key.path}"))
    (defconst my-gemini-api-key (my/read-secret "${config.sops.secrets.gemini_api_key.path}"))
    (defconst my-openrouter-api-key (my/read-secret "${config.sops.secrets.openrouter_api_key.path}"
    (defconst my-deepseek-api-key (my/read-secret "${config.sops.secrets.deepseek_api_key.path}"))

    (provide 'secrets)
  '';
}
